name: Container Action Tests

on:
  push:
    branches:
      - prime
      - develop
  pull_request_review:
    types: [submitted]

permissions:
  contents: read
  packages: write

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Create test Dockerfile
        run: |
          echo 'FROM alpine:latest
          ARG MY_ENV_VAR
          ARG MY_ENV_VAR2
          ENV MY_ENV_VAR=$MY_ENV_VAR
          ENV MY_ENV_VAR2=$MY_ENV_VAR2
          ARG EXTRA_ENV_VAR
          ARG EXTRA_ENV_VAR2
          ENV EXTRA_ENV_VAR=$EXTRA_ENV_VAR
          ENV EXTRA_ENV_VAR2=$EXTRA_ENV_VAR2
          CMD ["sh", "-c", "echo Result: $MY_ENV_VAR $MY_ENV_VAR2 ~$EXTRA_ENV_VAR~ ~$EXTRA_ENV_VAR2~"]' > Dockerfile
          cat Dockerfile
      - name: Use Build and Push action
        uses: ./
        with:
          login_registry: ghcr.io
          login_username: ${{ github.actor }}
          login_password: ${{ secrets.GITHUB_TOKEN }}
          tags: ghcr.io/frozen-tapestry/podman-action-verify:latest ghcr.io/frozen-tapestry/podman-action-verify:test
          dockerfile: Dockerfile
          build_args: MY_ENV_VAR=Test MY_ENV_VAR2=Test2
          extra_args: --build-arg EXTRA_ENV_VAR="Extra\ env\ 1" --build-arg=EXTRA_ENV_VAR2=Extra\ env\ 2
          labels: com.example.test-label=test\ label
          annotations: com.example.test-annotation=annotation
          security: |
            --security-opt=seccomp=unconfined
            --security-opt=apparmor=unconfined
          push: true
      - name: Run Docker container and verify output
        id: verify-output
        run: |
          LATEST="ghcr.io/frozen-tapestry/podman-action-verify:latest"
          OUTPUT=$(docker run --rm "$LATEST")
          OUTPUT2=$(docker run --rm ghcr.io/frozen-tapestry/podman-action-verify:test)
          OUTPUT_LABEL=$(docker inspect "$LATEST" | jq -r ".[0].Config.Labels[\"com.example.test-label\"]")
          OUTPUT_ANNOTATION=$(docker manifest inspect "$LATEST" | jq -r '.annotations["com.example.test-annotation"] // .manifests[].annotations["com.example.test-annotation"]')
          echo "Container Output: $OUTPUT"
          echo "Container Output2: $OUTPUT2"
          echo "Container label: $OUTPUT_LABEL"
          echo "Container annotation: $OUTPUT_ANNOTATION"
          
          if [ "$OUTPUT" != "Result: Test Test2 ~\"Extra env 1\"~ ~Extra env 2~" ] ||
             [ "$OUTPUT" != "$OUTPUT2" ] ||
             [ "$OUTPUT_LABEL" != "test label" ] ||
             [ "$OUTPUT_ANNOTATION" != "annotation" ]; then
            echo "Output does not match expected string"
            exit 1
          fi